apiVersion: apps/v1
kind: Deployment
metadata:
  name: studybuddy-frontend
  labels:
    app: studybuddy-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: studybuddy-frontend
  template:
    metadata:
      labels:
        app: studybuddy-frontend
    spec:
      containers:
        - name: studybuddy-frontend
          image: ilyes111/studybudyy-frontend:latest
          ports:
            - containerPort: 8086   # Exposing container port 8086
          command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]  # Ensure app binds to 0.0.0.0
