apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-service
  labels:
    app: chatbot-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-service
  template:
    metadata:
      labels:
        app: chatbot-service
    spec:
      containers:
        - name: chatbot-service
          image: ilyes111/chatbot-service:latest
          ports:
            - containerPort: 8085