apiVersion: v1
kind: Service
metadata:
  name: studybuddy-frontend
  labels:
    app: studybuddy-frontend
spec:
  selector:
    app: studybuddy-frontend
  ports:
    - port: 80           # Port exposed by the service
      targetPort: 8086   # Port exposed by the container
      nodePort: 30086    # External port for accessing the service
  type: NodePort
