apiVersion: v1
kind: Service
metadata:
  name: calendar-service
  labels:
    app: calendar-service
spec:
  selector:
    app: calendar-service
  ports:
    - port: 5002          # Port exposed by the service
      targetPort: 8084   # Port exposed by the container
      nodePort: 30084    # External port for accessing the service
  type: NodePort
