apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
  labels:
    app: chatbot-service
spec:
  selector:
    app: chatbot-service
  ports:
    - port: 80           # Port exposed by the service
      targetPort: 8085   # Port exposed by the container
      nodePort: 30085    # External port for accessing the service
  type: NodePort
