apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  labels:
    app: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - port: 5003           # Port exposed by the service
      targetPort: 8082   # Port exposed by the container
      nodePort: 30082    # External port for accessing the service
  type: NodePort
