apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  selector:
    app: auth-service
  ports:
    - port: 80           # Port exposed by the service
      targetPort: 8083   # Port exposed by the container
      nodePort: 30083    # External port for accessing the service
  type: NodePort
